# Form implementation generated from reading ui file '.\redesign\add_section_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiAddSectionDialog(object):
    def setupUi(self, add_section_dialog):
        add_section_dialog.setObjectName("add_section_dialog")
        add_section_dialog.resize(500, 178)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_section_dialog.sizePolicy().hasHeightForWidth())
        add_section_dialog.setSizePolicy(sizePolicy)
        add_section_dialog.setStyleSheet("* {\n"
"    font: 12pt \"Montserrat\";\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-weight: 500;\n"
"    color: #fff;\n"
"    background-color: #E30617;\n"
"    padding: 5px 10px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f60c1e;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #ff99a1;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit {\n"
"    padding: 2px 4px;\n"
"    border: 1px solid #A2B6C1;\n"
"    border-radius: 3px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(add_section_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=add_section_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font-weight: 500;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.widget = QtWidgets.QWidget(parent=add_section_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.section_name_input = QtWidgets.QLineEdit(parent=self.widget)
        self.section_name_input.setObjectName("section_name_input")
        self.verticalLayout_2.addWidget(self.section_name_input)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=add_section_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirm_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout.addWidget(self.confirm_button)
        self.cancel_button = QtWidgets.QPushButton(parent=self.widget_2)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(add_section_dialog)
        QtCore.QMetaObject.connectSlotsByName(add_section_dialog)

    def retranslateUi(self, add_section_dialog):
        _translate = QtCore.QCoreApplication.translate
        add_section_dialog.setWindowTitle(_translate("add_section_dialog", "Добавление раздела"))
        self.label_2.setText(_translate("add_section_dialog", "Добавление раздела"))
        self.label.setText(_translate("add_section_dialog", "Название"))
        self.confirm_button.setText(_translate("add_section_dialog", "Добавить"))
        self.cancel_button.setText(_translate("add_section_dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_section_dialog = QtWidgets.QDialog()
    ui = Ui_add_section_dialog()
    ui.setupUi(add_section_dialog)
    add_section_dialog.show()
    sys.exit(app.exec())
